In [2]:
from sklearn import svm
import pandas as pd
import math

data = pd.read_csv('zoo.csv')
data.head(6)

animal_name  hair  feathers  eggs  milk  airborne  aquatic  predator  \
0    aardvark     1         0     0     1         0        0         1   
1    antelope     1         0     0     1         0        0         0   
2        bass     0         0     1     0         0        1         1   
3        bear     1         0     0     1         0        0         1   
4        boar     1         0     0     1         0        0         1   
5     buffalo     1         0     0     1         0        0         0   

   toothed  backbone  breathes  venomous  fins  legs  tail  domestic  catsize  \
0        1         1         1         0     0     4     0         0        1   
1        1         1         1         0     0     4     1         0        1   
2        1         1         0         0     1     0     1         0        0   
3        1         1         1         0     0     4     0         0        1   
4        1         1         1         0     0     4     1         0        1   
5        1         1         1         0     0     4     1         0        1   

   class_type  
0           1  
1           1  
2           4  
3           1  
4           1  
5           1

In [3]:
from sklearn.model_selection import train_test_split

all_x = data.iloc[:, 1:17] # all rows, features only, no labels
all_y = data.iloc[:,17]    # all rows, label only, no features

x_train, x_test, y_train, y_test = train_test_split(all_x, all_y)

In [4]:
print(x_train.shape, x_test.shape, y_train.shape, y_test.shape)

(75, 16) (26, 16) (75,) (26,)


In [5]:
clf = svm.SVC()
clf.fit(x_train, y_train)

SVC()

In [6]:
clf.score(x_test, y_test)

1.0

In [7]:
clf.predict(x_test[10:15])

array([4, 1, 2, 5, 1])

In [8]:
# show what the correct answer is
y_test[10:15]

60    4
17    1
20    2
52    5
28    1
Name: class_type, dtype: int64

In [9]:
import numpy as np
from sklearn.model_selection import train_test_split
X, y = np.arange(10).reshape((5, 2)), range(5)
print(X)
list(y)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


[0, 1, 2, 3, 4]

In [10]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [11]:
X_train

array([[4, 5],
       [0, 1],
       [6, 7]])

In [12]:
y_train

[2, 0, 3]

In [13]:
X_test

array([[2, 3],
       [8, 9]])

In [14]:
y_test

[1, 4]